### PR TITLE
unit test for BirchClustering

### PR DESCRIPTION
**Pull request by JiQi535**
I'm adding unit tests for DIRECT sampling. If this looks fine, I will complete the other parts shortly this week.

### CODE REVIEW

**Comment by shyuep** [comment]
This does not look like unittests. A unittest should test the outcome of an operation. All this tests is that the code actually runs without error.

**Comment by shyuep** [comment]
This is better. But I would prefer you to use proper pytest syntax. In other words, the classes should be named TestXX not XXTest, and instead of setUp, you use setup or pytest fixtures. You are already using assert statements. So that is fine.

**Comment by shyuep** [comment]
I should also say that you need to add in the documentation for all parts of the methods.

**Comment by JiQi535** [comment]
> This is better. But I would prefer you to use proper pytest syntax. In other words, the classes should be named TestXX not XXTest, and instead of setUp, you use setup or pytest fixtures. You are already using assert statements. So that is fine.

Thanks for the comments! I have changed to pytest fixtures. I personally feel that it makes the code a bit harder to understand, as people may not know where these variables are defined. But I agree that this is an overall better implementation, as we don't need to load same data multiple times. 

Does these test classes look okay? @shyuep I will add in documentations and other modifications in next PR.

**Comment by shyuep** [comment]
This is good. I have merged this PR.

**Pull request merged**
